### ISSUE TITLE
destroy function

### ISSUE THREAD

**Issue by GitMax42** [sachinchoolur/lightgallery.js#102]
Why does Plugin.prototype.destroy do a scrollTop ?

document.body.scrollTop = _this.prevScrollTop;
document.documentElement.scrollTop = _this.prevScrollTop;

**Comment by parisek** [comment]
Duplicate issue https://github.com/sachinchoolur/lightgallery.js/issues/78

**Comment by unnamedfeeling** [comment]
There is simple fix for this issue:
`window.lgData[lgContainer.getAttribute('lg-uid')].prevScrollTop = window.pageYOffset;
 window.lgData[lgContainer.getAttribute('lg-uid')].destroy(true);`
