### ISSUE TITLE
No function of rotating the picture

### ISSUE THREAD

**Issue by ZengFanhui** [sachinchoolur/lightgallery.js#104]
can author add this fucntion?

**Comment by kuoruan** [comment]
I wrote a plugin, you can have a try
```
const rotateDefaults = {
  rotate: true,
  rotateAngle: 0
}

const Rotate = function (element) {
  this.el = element

  this.core = window.lgData[this.el.getAttribute('lg-uid')]
  this.core.s = Object.assign({}, rotateDefaults, this.core.s)

  this.init()

  return this
}

Rotate.prototype.init = function () {
  if (this.core.s.rotate) {
    const rotate = '<span class="lg-rotate lg-icon"></span>'
    this.core.outer.querySelector('.lg-toolbar').insertAdjacentHTML('beforeend', rotate)
    this.rotate()
  }
}

Rotate.prototype.rotate = function () {
  const setRotate = function (elment, rotate) {
    if (!elment) return

    utils.setVendor(elment, 'Transform', `rotate(${rotate}deg)`)
  }

  const _self = this

  const el = this.core.outer.querySelector('.lg-rotate')
  /* global utils */
  utils.on(el, 'click.lg', function () {
    const element = _self.core.___slide[_self.core.index]
    const angle = (+element.getAttribute('data-rotate')) + 90

    setRotate(element, angle)
    element.setAttribute('data-rotate', angle)
  })

  utils.on(this.core.el, 'onSlideItemLoad.lgtm onBeforeSlide.lgtm', function (event) {
    const angle = _self.core.s.rotateAngle
    const element = _self.core.___slide[event.detail.index]

    setRotate(element, angle)
    element.setAttribute('data-rotate', angle)
  })
}

Rotate.prototype.destroy = function () {
}

window.lgModules.rotate = Rotate
```

**Comment by ZengFanhui** [comment]
oh,thank you!
I've tried to write before, but I haven't managed the position after the rotation and the conflict with the zoom plugin

**Comment by yoldar** [comment]
I guess it would be better to make rotating in zoom plugin

**Comment by aMarstd** [comment]
What is utils? - http://prntscr.com/n3r0ew

We get this error - http://prntscr.com/n3r0xo
http://prntscr.com/n3r199

**Comment by imarshmultani** [comment]
i did add rotation functionality on my own and it just works as it should ... was waiting for official update , but nothing in here so had to do it on my own ... 

Let me know if anyone still looking for this ...

**Comment by smilingpigs** [comment]
@imarshmultani yes, can you please share your code?

**Comment by stransky87** [comment]
@imarshmultani pls share this code ;-)

**Comment by roypardi** [comment]
@imarshmultani  – yes, if that "rotate" code is available I'd love to take a look. I'm trying to write an "annotation" plugin and am searching out examples to learn from.

**Comment by 0xda203** [comment]
const defaults = {
      rotate: true,
      rotateAngle: 0,
      appendRotateControlsTo: '.lg-toolbar'
    }

    /**
     * Creates the rotate plugin.
     * @param {object} element - lightGallery element
     */
    var Rotate = function(element) {
      this.core = $(element).data('lightGallery');
      this.$el = $(element);

      this.core.s = $.extend({}, defaults, this.core.s);
      this.init();
      return this;
    }

    Rotate.prototype.init = function() {
        var _this = this;
        if (this.core.s.rotate) {
           // append rotate controls
           _this.controls();
        }
    }

    // Manage rotate via rotate buttons
    Rotate.prototype.controls = function() {

      const setRotate = function ($image, rotationAngle) {
        $image.css('transform', 'rotate(' + rotationAngle + 'deg)');
      }

      var _this = this;
      var _html = '<span class="lg-rotate lg-icon"></span>';

      // Append rotate controls
      $(this.core.s.appendRotateControlsTo).append(_html);

      _this.core.$outer.find('.lg-rotate').on('click.lg', function() {
        // Get the current element
        var $image = _this.core.$slide.eq(_this.core.index).find('.lg-image');
        const angle = parseInt($image.attr('data-rotate')) + 90;

        setRotate($image, angle);
        $image.attr('data-rotate', angle);
      });

      // Add rotate class
      _this.core.$el.on('onSlideItemLoad.lg.tm onBeforeSlide.lg.tm', function(event, index) {
        const angle = _this.core.s.rotateAngle;
        var $image = _this.core.$slide.eq(index).find('.lg-image');

        setRotate($image, angle);
        $image.attr("data-rotate", angle)
      });
    };

    Rotate.prototype.destroy = function() {};

    $.fn.lightGallery.modules.rotate = Rotate;

You'll also need a lg-rotate class:
`.lg-rotate:after {
    content: "↻";
}`

**Comment by roypardi** [comment]
@gabl00n  – thanks! That works great. Will learn a lot from it!
