### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by mhardaniel** [sachinchoolur/lightgallery.js#106]
npm package is not latest version and not working
but when using cdn version it has no issue.. thanks..

**Comment by vielhuber** [comment]
This is the newest version: https://www.npmjs.com/package/lightgallery.js

**Comment by UisgeBeatha436** [comment]
This version is without the additional modules. Correct? How do I install these if I don't want to use the jQuery version? This command `npm install lightgallery.js`doesn't install any module, as far as I'm aware.

**Comment by stof** [comment]
The additional modules are available as separate npm packages (for instance https://www.npmjs.com/package/lg-zoom.js)
