### ISSUE TITLE
Events don't work

### ISSUE THREAD

**Issue by Findus23** [sachinchoolur/lightgallery.js#108]
Hi,

I have tried adding lightgallery to my site and it works really well. But there is one issue left: I can't get events to work.

Reading [the docs](https://sachinchoolur.github.io/lightgallery.js/docs/api.html#events) it seems like the following should work, but while the gallery displays fine, nothing gets logged.
```html
<div id="galleryElement"></div>
```
```javascript
var galleryElement = document.getElementById("galleryElement");

var els = [{
    src: "https://sachinchoolur.github.io/lightgallery.js/static/img/1-1600.jpg"
}];
galleryElement.addEventListener("lgOnBeforeClose", function () {
    alert("closed");
});
galleryElement.addEventListener("lgOnBeforeOpen", function (e) {
    alert("onBeforeOpen");
}, false);

lightGallery(galleryElement, {
    dynamic: true,
    dynamicEl: els
});
```
Codepen for reproducing:
https://codepen.io/anon/pen/MqwYoN

**Comment by Findus23** [comment]
Turns out that unlike the examples in the docs, the events are called `onBeforeClose` and `onBeforeOpen`.

**Comment by tomhalley** [comment]
Well the documentation is out of date, so this shouldn't be closed.

Also having to deal with these events, and I can't even get `onBeforeClose` and `onBeforeOpen` working on my project:

```
const lightGalleryElement = document.getElementById('Gallery');
           
lightGalleryElement.addEventListener('onBeforeOpen', function() {
    console.log('Hello World');
});
```

**Comment by taras2358** [comment]
In case someone experiences the same issue:
https://sachinchoolur.github.io/lightGallery/docs/api.html#events
