### ISSUE TITLE
Destroying lightgallery.js?

### ISSUE THREAD

**Issue by rdpascua** [sachinchoolur/lightgallery.js#11]
I can't destroy the lightgallery, I'm using

```
lightGallery().destroy()
```

is this the right way to destroy this lib? Also I can't get this to work with webpack

**Comment by sachinchoolur** [comment]
Hi,
There was an issue with docs. It's updated now.
Demo: https://sachinchoolur.github.io/lightgallery.js/demos/methods.html
Docs: https://sachinchoolur.github.io/lightgallery.js/docs/api.html#methods

It works fine with RequireJS and Browserify. I haven't tried lightgallery.js with webpack yet,  any help with this would be much appreciated.

**Comment by sachinchoolur** [comment]
Hi,
There was as issue with docs. It's updated now. You have to use  `require('lightgallery.js')` instead of `require('lightgallery')` as the package name is `lightgallery.js`

**Comment by rdpascua** [comment]
I don't know webpack but I'll be willing to help if I have time. Thanks anyway

**Comment by sachinchoolur** [comment]
Hi @rdpascua,
The issue has already been fixed.  :)

Thanks
