### ISSUE TITLE
Request to add `aria-modal="true"` to modal div

### ISSUE THREAD

**Issue by jitendersandhu** [sachinchoolur/lightgallery.js#110]
Hi @sachinchoolur,

We have been trying to make our website accessibility compliant (as per standards [here](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/dialog-modal/dialog.html)) and in our effort to do that, we are adding `aria-modal="true"` to all the modals used in our website and `lightgallery` is one of them.

Could you please add the `aria-modal="true"` attribute to the `.lg-outer` `div` so that it can help us and everyone else, who is using this **super awesome** library, to make the web more accessible for users.

Suggestion: An option can be added `accessible: true` and if set, add `aria-modal="true"` to outer div inside the template [here](https://github.com/sachinchoolur/lightgallery.js/blob/master/src/js/lightgallery.js#L311). 

Please let us know if you want a PR for this feature request and thanks again for making such an awesome library!

Cheers,
Jitender Singh

**Comment by jitendersandhu** [comment]
@sachinchoolur - Any updates on this please?

**Comment by jitendersandhu** [comment]
@sachinchoolur - Any updates on this please?

**Comment by sachinchoolur** [comment]
Hey @jitendersandhu,

This has been fixed in version 2 - https://www.lightgalleryjs.com/
V2 is completely accessible.

Sorry for not responding on time
