### ISSUE TITLE
White blank page when opened with some firefox add-ons enabled.

### ISSUE THREAD

**Issue by sam555** [sachinchoolur/lightgallery.js#12]
Blank white page when following add-ons are enabled in firefox-

1)Owl- for comfortable reading
![owloff](https://cloud.githubusercontent.com/assets/8680519/17426873/a2d9d7ec-5af9-11e6-9534-aa0d3429215e.jpg)
![owlon](https://cloud.githubusercontent.com/assets/8680519/17426871/a2d653b0-5af9-11e6-818d-d44c73205872.jpg)

2)Night Mode Pro
![nightoff](https://cloud.githubusercontent.com/assets/8680519/17426872/a2d938be-5af9-11e6-984b-ab0dcf99a88d.jpg)
![nighton](https://cloud.githubusercontent.com/assets/8680519/17426870/a2d358d6-5af9-11e6-8bab-ddf8ef12b53e.jpg)

**Comment by sachinchoolur** [comment]
Hi,
I'm sorry, The issue is not related to lightgallery.js. It's related to add-ons, they are updating the DOM.
