### ISSUE TITLE
Same instance, various images on the page

### ISSUE THREAD

**Issue by arnaudthuillier** [sachinchoolur/lightgallery.js#122]
Hello,

Here is my case : 
- I have a main image "gallery" (4 images)
- Further down in the page I have another one (1 image)

My question :
I want the images from both gallery be part of the same instance of lightGallery - with the 5 images - is that possible ?

Thank you

**Comment by vielhuber** [comment]
Yes, for sure.

Checkout this gist, which exactly does that:
https://gist.github.com/vielhuber/6bb460e96c42031d96d09f7a29bb6e7a

**Comment by arnaudthuillier** [comment]
Thank you !
