### ISSUE TITLE
Problem with src using owl-carousel and lightGallery 

### ISSUE THREAD

**Issue by Heldegar** [sachinchoolur/lightgallery.js#127]
Hello i want to use owl-carousel and lightGallery but i got this : 
![zeze](https://user-images.githubusercontent.com/19143393/52444417-9af5d880-2b28-11e9-9285-80b753937a98.png)
with the error : "lightGallery :- data-src is not pvovided on slide item 27. Please make sure the selector property is properly configured"

```
<div id="selector1" class="owl-carousel owl-theme">

       <?php while ($row = mysqli_fetch_array($queryycf))  

            {
                $miniature=$row['photominiature'];
               echo'<div class="item"><a href="'.$miniature.'"> <img class="img-fluid" src="'.$miniature.'"></a></div> ';
            }
        ?>
        </div>
```

Do you got any issues ? thanks a lot !

**Comment by egerb** [comment]
Try add to you <a data-src ="your_link" > tag attribute data-src.
If doesn't work, try manually set selector for lightgallery using {selector}.
