### ISSUE TITLE
How to use in for angular 2.

### ISSUE THREAD

**Issue by ranjeet-floyd** [sachinchoolur/lightgallery.js#13]

**Comment by sachinchoolur** [comment]
Hi,
Currently, I don't have any plan to release AngularJs version. But I will definitely consider it if I get enough time.

**Comment by azharuniverse** [comment]
Here's is an angular porting 
https://www.npmjs.com/package/angular-lightgallery

**Comment by Chethannp** [comment]
Hey Sachinchoolur, do we have an angular 2 version of it now ? can you please help! All my 6 projects use lightgalleryjs and now I am developing an ionic 3 angular 4 project and was unable to get an info about your plugin.  requesting you to kindly update on this please.

**Comment by abe312** [comment]
https://www.npmjs.com/package/angular-lightgallery that's buggy and for angularJS and the fix requires jQuery version.

**Comment by sachinchoolur** [comment]
Using lightgallery.js with Angular -  https://github.com/sachinchoolur/lightgallery.js/issues/161
