### ISSUE TITLE
Error when trying to change slide in vanilla JS version

### ISSUE THREAD

**Issue by youradds** [sachinchoolur/lightgallery.js#132]
Hi,

As per your instructions, I'm trying to programatically change the slide we are on: 

		            	var gallery_el = document.getElementById('the-gallery');
		                window.VARS.gallery = lightGallery(gallery_el, {
		                    thumbnail:true,
		                    controls: true,
		                    dynamicEl: window.VARS.gallery_photos,
		                    download: false,
		                    counter: false,
		                    dynamic: true,
		                    index: window.VARS.goto_slide // this works first time, but not on re-opening when you want a differentone
		                });

   
		                console.dir(window.lgData[gallery_el.getAttribute('lg-uid')]);
		                console.log("FOO: " + gallery_el.getAttribute('lg-uid') + " , on " + window.VARS.goto_slide)
						window.lgData[gallery_el.getAttribute('lg-uid')].slide(window.VARS.goto_slide);

I get an error:

> TypeError: t is undefined

The debug seems ok:

> FOO: lg0 , on 1

I don't seem to be able to see the slide() function though, so maybe I'm missing something?

> ___slide: NodeList(5)
​​
0: <div class="lg-item" lg-event-uid="&32">​​
1: <div class="lg-item lg-current" lg-event-uid="&33">​​
2: <div class="lg-item" lg-event-uid="&34">​​
3: <div class="lg-item" lg-event-uid="&35">​​
4: <div class="lg-item" lg-event-uid="&36">
​​
length: 5
​​
<prototype>: NodeListPrototype { item: item(), keys: keys(), values: values(), … }
​
el: <div id="the-gallery" class="photo-gallery" lg-uid="lg0" lg-event-uid="&3&14">
​
hideBartimeout: false
​
index: 1
​
isTouch: false
​
items: Array(5) [ {…}, {…}, {…}, … ]
​
lGalleryOn: false
​
lgBusy: true
​
modules: Object { thumbnail: {…} }
​
outer: <div class="lg-outer lg-start-zoom l…has-thumb lg-can-toggle" lg-event-uid="&27&28&29&30&31">
​
prevScrollTop: 408
​
s: Object { thumbnail: true, animateThumb: true, currentPagerPosition: "middle", … }
​
<prototype>: {…

**Comment by romanlex** [comment]
+1
https://github.com/sachinchoolur/lightgallery.js/issues/134
