### ISSUE TITLE
index option with dynamic doesn't work

### ISSUE THREAD

**Issue by romanlex** [sachinchoolur/lightgallery.js#134]
Hello. I found what index option doesn't work properly with `dynamic: true`
I always see first image

**Comment by deadlious** [comment]
try using something like this:

function load_gallery(sl){
                let gal = document.getElementById('lightgallery');
                let lst = get_list(gal);
                lg = lightGallery(gal, {
                    dynamic: true,
                    dynamicEl: lst,
                    preload: 2,
                    responsive: true,
                    thumbnail: true
                });
                pl = window.lgData[gal.getAttribute('lg-uid')];
                pl.index = parseInt(sl);
                document.getElementById('my_slider').innerHTML = sl;
                setTimeout(function () {
                    pl.slide(parseInt(document.getElementById('my_slider').innerHTML));
                });

the function is called by "onclick" event

**Comment by vwong** [comment]
My experience:

While the main image changes correctly to the desired slide number with `window.lgData[galleryId].slide(desiredSlideNumber)`, the selected thumbnail remains at slide 1.

**Comment by sachinchoolur** [comment]
Dynamic mode with index works fine - Here is the demo - https://codepen.io/lightGallery/pen/bGBYOPr

Please make sure you are passing a number as an index instead of a string value

**Comment by vwong** [comment]
Ah, you're invoking it a different way. This works for me. Thanks!

**Comment by nlemoine** [comment]
@sachinchoolur I'm having similar issues with `index` option when used with `dynamic: true`. Please consider the following example: https://codepen.io/hellonico/pen/QWGoRqp

(forked from yours)


The right index is ok when opening the first time but it stays the same on subsequent clicks on different items.

Steps to reproduce:
1. Click on one item (1,2,3,4)
2. Item opened it the right index
3. Close the gallery
4. Click on a another item (not the same one)
5. Item opened is the first one you opened in first step

**Comment by nlemoine** [comment]
Related #34

**Comment by CCCullens** [comment]
I create a lot of dynamic galleries and often open a specific slide. I have found that after the gallery is closed, it's best to from a DOM level, to "removeChild()" the element the LG was attached to. See https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove


TypeScript excerpts - pseudo code, I have a class variable that is the element the LG was created on
    public DestroyLightGalleryElement(): void {
        // only remove it if it exist
        if (this.CreateLightGalleryDivChild !== null) {
            this.CreateLightGalleryDivParent.removeChild(this.CreateLightGalleryDivChild)
            this.CreateLightGalleryDivChild = null as any
        }
    }


... found in my close gallery event code
       lg.on('onCloseAfter.lg', () => {
            if (lg.data('lightGallery') !== undefined) {
                if (lg.data('lightGallery').destroy !== undefined) {
                    lg.data('lightGallery').destroy(true)
                }
            }
            cc.DestroyLightGalleryElement()
        })
`

Might be overkill, but always works :-)

**Comment by nlemoine** [comment]
@CCCullens That you lose all the caching done by the library. 

I found a workaround using this code (which is triggered on click on a thumbnail):
```js
const galleryId = galleryNode.getAttribute('lg-uid');
if(galleryId) {
    EventHandler.one(galleryNode, 'onBeforeOpen', (e) => {
      window.lgData[galleryId].s.index = index;
      window.lgData[galleryId].s.dynamicEl = itemsDynamic;
    });
}
```

It seems that options passed are not updated when calling the instance again. I have a filterable grid of thumbnails and have to update dynamic items depending of selected filters (that's why I update `index` and `dynamicEl`).

**Comment by CCCullens** [comment]
Correct, I lose any LG caching. I do not lose the browser caching of the photos. By design, my app already has fetched all photos that I dynamically use LG to display. That said, good to know about the onBeforeOpen solution, thanks.

**Comment by sachinchoolur** [comment]
Please use this workaround for now. I've added a public method to open gallery with a specific index.  This can be used to open dynamic gallery with clicked index. 

![Dynamic-Mode-lightGallery](https://user-images.githubusercontent.com/6586706/111284531-33df7200-8666-11eb-9cd0-243c93d13562.png)

This will be released in the next version

**Comment by nlemoine** [comment]
Thanks @sachinchoolur! How about a method that updates the instance? In my example, I also have to update `dynamicEl`.

**Comment by sachinchoolur** [comment]
If you need to update `dynamicEl`, you can destroy lightGallery and re-initiate with a new set of `dynamicEl`

https://sachinchoolur.github.io/lightgallery.js/demos/methods.html

**Comment by nlemoine** [comment]
Thanks for the tip.
