### ISSUE TITLE
addClass Error

### ISSUE THREAD

**Issue by shuxikql** [sachinchoolur/lightgallery.js#14]
When I try the html5 videos, I have the error.
<img width="719" alt="2016-08-05 4 25 28" src="https://cloud.githubusercontent.com/assets/19688432/17430867/5d449e58-5b29-11e6-9104-71fdd82b13b4.png">

**Comment by sachinchoolur** [comment]
HI,
The issue has been fixed. Please use the latest version of video module. https://github.com/sachinchoolur/lg-video.js
