### ISSUE TITLE
Unable to data bind to data-src

### ISSUE THREAD

**Issue by p-sheth** [sachinchoolur/lightgallery.js#15]
<a  href="" data-src="{{image.imageUrl}}">
                            <img class="img-responsive" src="{{image.imageUrl}}" alt="" >
                            <div class="overlay">
                              {{image.searchData.State}}
                            </div>
                            </a>

gives interpolation error

**Comment by sachinchoolur** [comment]
It is not an issue with lightgallery.js. Anyway, you can use href instead of data-src.

``` html
 <a  href="{{image.imageUrl}}">
                            <img class="img-responsive" src="{{image.imageUrl}}" alt="" >
                            <div class="overlay">
                              {{image.searchData.State}}
                            </div>
                            </a>
```
