### ISSUE TITLE
Do the Comments have to use Facebook, or can I build my own interaction?

### ISSUE THREAD

**Issue by ghost** [sachinchoolur/lightgallery.js#16]
As per the title. Is the comments addon reliant on Facebook, or can I modify it to use my own comments system on the backend?

Also, is it possible to only have particular images be able to have comments?

**Comment by sachinchoolur** [comment]
Hi,
Currently, I've only facebook comments demo. But it won't be hard to integrate your own comment system. You are free to fork the repo and modify it however you want.
