### ISSUE TITLE
How do I remove the share and download buttons?

### ISSUE THREAD

**Issue by simoneliv94** [sachinchoolur/lightgallery.js#160]
I am trying to remove those two button that I actually don't need, but I can't find a way to do this.

**Comment by DigitalZebra** [comment]
I think you want to pass `download` and `share` as `false` via the options, at least according to the docs: https://sachinchoolur.github.io/lightgallery.js/docs/api.html

Here's an example:
```
lightGallery(document.getElementById("gallery"), {
  download: false,
  share: false,
});
```

**Comment by sachinchoolur** [comment]
Yes, you can remove the download and share buttons by passing the respective options via settings. 
If you need to remove the download button for a particular slide, you can pass `false` in data-download-url - 
Docs - https://sachinchoolur.github.io/lightgallery.js/docs/api.html

And if you don't need the share option at all, you don't have to include the share plugin

**Comment by stagebyte** [comment]
Hi @sachinchoolur, thanks for your support. I have been struggling with adding thumbnails to the inline styles using react but doesn't work for them. It clearly shows a space where the thumbnails show appears but it appears as if the thumbnails are either hiding or they are missing. Please kindly assist me. Thanks.

**Comment by sachinchoolur** [comment]
Hey @stagebyte,

Could you please share a screenshot of the issue? Or a stackblitz demo if possible
