### ISSUE TITLE
How to add two separate galleries on the same page? (Code is attached, which is not working)

### ISSUE THREAD

**Issue by iwllu** [sachinchoolur/lightgallery.js#170]
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <title>lightGallery: thumbnails</title>
        <meta name="description" content="lightGallery lets you to create animated thumbnails for your gallery with the help of thumbnail plugin." />
        <link href="../static/css/main.css" rel="stylesheet">
        <link href="../static/css/justifiedGallery.min.css" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
        <link href="../lightgallery/css/lightgallery.css" rel="stylesheet">
        <link rel="shortcut icon" href="../favicon.ico" type="image/x-icon">
        <link rel="icon" href="../favicon.ico" type="image/x-icon">
        
    </head>
    <body class="demos">
        
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="http://sachinchoolur.github.io/lightgallery.js/">lg</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="../">Home<span class="border"></span></a></li>
                        <li><a href="../docs/">Docs<span class="border"></span></a></li><li> <a href="../docs/license.html">License<span class="border"></span></a></li>
                        <li class="active"><a href="../demos/">Demos<span class="border"></span></a></li>
                        <li><a target="_blank" href="https://github.com/sachinchoolur/lightgallery.js">Github<span class="border"></span></a></li>
                        <li><a target="_blank" href="http://sachinchoolur.github.io/lightGallery/" onclick="ga('send', 'event', 'lg', 'lg');">jQuery lightGallery<span class="border"></span></a></li> 
                        
                    </ul>
                </div>
            </div>
        </nav>
        <section class="section pdb0">
            <div class="container-fluid">
                <div class="section-header has-desc mrb50">
                    <h1 class="page-header mrb15">Gallery with animated thumbnails</h1>
                    <p>Lightgallery allows you to create animated thumbnails for your gallery with the help of thumbnail plugin. It supports touch swipe navigation on touchscreen devices as well as mouse drag for desktops. It also allows users to navigate between thumbnails via swipe of their fingers or mouse drag. </p>
                </div>
                <div class="demo-gallery mrb50">
                    <div id="aniimated-thumbnials" class="list-unstyled">
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/1.jpg" data-sub-html="sdsdsd">
                            <img class="img-responsive" src="../static/img/thumb-1.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/2.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-2.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/3.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-3.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/4.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-4.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/5.jpg" data-sub-html="sdsdsd">
                            
                            <img class="img-responsive" src="../static/img/thumb-5.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/6.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-6.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/7.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-7.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/8.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-8.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/9.jpg" data-sub-html="sdsdsd">
                            
                            <img class="img-responsive" src="../static/img/thumb-9.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/10.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-10.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/11.jpg" data-sub-html="sdsdsd">
                            
                            <img class="img-responsive" src="../static/img/thumb-11.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/12.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-12.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/13.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-13.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/14.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-14.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/15.jpg" data-sub-html="sdsdsd">
                            
                            <img class="img-responsive" src="../static/img/thumb-15.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/16.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-16.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/17.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-17.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/18.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-18.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/19.jpg" data-sub-html="sdsdsd">
                            
                            <img class="img-responsive" src="../static/img/thumb-19.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/20.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-20.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                    </div>
                </div>

            </div>
        </section>

        <section class="section pdb0">
            <div class="container-fluid">
                <div class="section-header has-desc mrb50">
                    <h1 class="page-header mrb15">Gallery with animated thumbnails</h1>
                    <p>Lightgallery allows you to create animated thumbnails for your gallery with the help of thumbnail plugin. It supports touch swipe navigation on touchscreen devices as well as mouse drag for desktops. It also allows users to navigate between thumbnails via swipe of their fingers or mouse drag. </p>
                </div>
                <div class="demo-gallery mrb50">
                    <div id="aniimated-thumbnials" class="list-unstyled">
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/1.jpg" data-sub-html="sdsdsd">
                            <img class="img-responsive" src="../static/img/thumb-1.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/2.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-2.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/3.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-3.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/4.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-4.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/5.jpg" data-sub-html="sdsdsd">
                            
                            <img class="img-responsive" src="../static/img/thumb-5.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/6.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-6.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/7.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-7.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/8.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-8.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/9.jpg" data-sub-html="sdsdsd">
                            
                            <img class="img-responsive" src="../static/img/thumb-9.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/10.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-10.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/11.jpg" data-sub-html="sdsdsd">
                            
                            <img class="img-responsive" src="../static/img/thumb-11.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/12.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-12.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/13.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-13.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/14.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-14.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/15.jpg" data-sub-html="sdsdsd">
                            
                            <img class="img-responsive" src="../static/img/thumb-15.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/16.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-16.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/17.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-17.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/18.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-18.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/19.jpg" data-sub-html="sdsdsd">
                            
                            <img class="img-responsive" src="../static/img/thumb-19.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                        <a data-pinterest-text="Pin it" data-tweet-text="share it on twitter" class="" href="../static/img/20.jpg">
                            
                            <img class="img-responsive" src="../static/img/thumb-20.jpg">
                            <div class="demo-gallery-poster">
                                <img src="../static/img/zoom.png">
                            </div>
                            
                        </a>
                    </div>
                </div>

            </div>
        </section>

        <footer>
            <a target="_blank" href="https://twitter.com/sachinchoolur"><img src="../static/img/social/twitter.png"></a>
            <a target="_blank" href="https://in.linkedin.com/in/sachinchoolur"><img src="../static/img/social/linked-in.png"></a>
        </footer>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="../static/js/prettify.js"></script>
        <script src="../static/js/jquery.justifiedGallery.min.js"></script>
        <script src="../static/js/transition.js"></script>
        <script src="../static/js/collapse.js"></script>
        <script src="../lightgallery/js/lightgallery.js"></script>
        <script src="../lightgallery/js/lg-thumbnail.js"></script>
        <script src="../lightgallery/js/lg-share.js"></script>
        <script src="../lightgallery/js/lg-fullscreen.js"></script>
        <script src="../lightgallery/js/lg-zoom.js"></script>
        <script src="../lightgallery/js/lg-autoplay.js"></script>
        <script src="../lightgallery/js/lg-hash.js"></script>
        <script src="../static/js/demos.js"></script>
    </body>
</html>

**Comment by sachinchoolur** [comment]
Here is the working demo - https://codepen.io/lightGallery/pen/eYZvqgw
Please let me know if you have any questions
