### ISSUE TITLE
Turn off hideControl

### ISSUE THREAD

**Issue by develth** [sachinchoolur/lightgallery.js#171]
Hello,

first of all, nice 'plugin'! I was searching for one that has a focus on accessibility and is also not a big toolset.

Is it possible to turn off the hideControl functionality? I just saw the option to raise delay, but not to turn it off. 

Thanks
Thomas

**Comment by sachinchoolur** [comment]
Hey @develth ,
Since version 1.4.0 you can pass `0` via `hideBarsDelay` option to turn off hideControls functionality
