### ISSUE TITLE
Drag orientation when image is rotated and zoomed

### ISSUE THREAD

**Issue by deadlious** [sachinchoolur/lightgallery.js#182]
Drag orientation is screwed when you rotate an image on 90 degrees, zoom it and try to drag it to a certain spot.
When rotated on 180 degrees, the image moves in the opposite direction of the drag direction.

**Comment by sachinchoolur** [comment]
Hey @deadlious,
Thank you for pointing this out. 
The issue has been fixed. Please use the latest version of [lg-rotate ](https://github.com/sachinchoolur/lg-rotate.js)and [lg-zoom](https://github.com/sachinchoolur/lg-zoom.js) plugins.

**Comment by deadlious** [comment]
Thank you! 👍
