### ISSUE TITLE
Gallery with videojs autoplay issue (lg-video.js ?)

### ISSUE THREAD

**Issue by ProUnebit** [sachinchoolur/lightgallery.js#184]
**Hey! lightgallery is great!**
But a i have a problem...
I use vanilla lightgallery.js in my project for videogallery with videojs. 
From this example http://sachinchoolur.github.io/lightGallery/demos/html5-videos.html#video-without-poster - i created 
similar code, but with lightgallery.js (no jQuery version) and added to options in videojs: true   and  videojsOptions: { autoplay: true}. It's works, but 
every video started in the same time with videojs. In example it works correctly - if i click chosen video exactly this video starts to play and other videos do not play! I need it to work like in the example (very need!!).
No errors in console and ect.
I've tried update lg-video.js and lightgallery core packeges, but this does not change anything!
**What am I doing wrong? I really need your help!**

**Comment by sachinchoolur** [comment]
Hey @ProUnebit,

You don't have to set `videojsOptions: { autoplay: true}` lightGallery takes care of the autoplay. 
Here is the working codepen demo - **https://codepen.io/lightGallery/pen/PozdEyx**

vanilla js HTML5 video demo - https://sachinchoolur.github.io/lightgallery.js/demos/html5-videos.html#video-without-poster


please let me know if you have any questions

**Comment by ProUnebit** [comment]
@sachinchoolur **oh, man, thanks a lot!**
I downgrade video.js (form **7.8.2** to **4.12** as in the example), removed videojsOptions: { autoplay: true} and it's perfectly works now! 

At the same time I will ask you:
How disable 'lg-thumb-open' class when I open my gallery? I want to open lg-thumb if i will need it, but i want to remove 'lg-thumb-open' start-behavior by default.

**Comment by sachinchoolur** [comment]
You can pass `showThumbByDefault : false` via options 
``` js
$('#lightGallery').lightGallery({
    videojs: true,
    showThumbByDefault: false,
})
```

Docs - https://sachinchoolur.github.io/lightGallery/docs/api.html

**Comment by ProUnebit** [comment]
@sachinchoolur thx, i overlooked this option!
You can close this topic, I have no more questions . . . presently 😁
