### ISSUE TITLE
link 404s

### ISSUE THREAD

**Issue by greg-minshall** [sachinchoolur/lightgallery.js#185]
under options, `dynamicEl`, the description has a link labeled "See example.":
````
https://sachinchoolur.github.io/lightgallery.js/docs/examples.html#dynamicBlock
````
 which 404s.

presumably it wanted to go to `https://sachinchoolur.github.io/lightgallery.js/demos/dynamic.html`?

**Comment by sachinchoolur** [comment]
Updated the link.

Thank you for pointing this out
