### ISSUE TITLE
Pictures and Yotube video in one gallery causes the video to autoplay even when not in focus

### ISSUE THREAD

**Issue by picarica** [sachinchoolur/lightgallery.js#186]
so i guess the issue is that the video autoplays anyways even when set not to, the generated iframe is like this
`<iframe class="lg-video-object lg-youtube lg-object" title="Kliknite pre spustenie" src="//www.youtube.com/embed/m2yr6EAWUz0?wmode=opaque&amp;autoplay=1&amp;enablejsapi=1&amp;autoplay=0" allowfullscreen="" width="560" height="315" frameborder="0"></iframe>`
i am not sure if its okay that there is passed autoplay=1 and autoplay=0 at the same time, yet this is my code

```
					    lightGallery(document.getElementById('gallery'), {
					        mode: 'lg-slide',
							loop: 'false',
							hideControlOnEnd:  'true',
							preload: 4,
							height: '100%',
							fullScreen: true,
							videoMaxWidth: '60%',
							autoplayFirstVideo: false,
							youtubePlayerParams: { autoplay: 0 }

					    }); 
```

i am using JS version of lightgallery with included lg-video in demo/js/lg-video.min.js

am i doing something wrong? the video also autoplay when clicked on directly, or when u open any of the pictures. what is the issue?

**Comment by sachinchoolur** [comment]
Autoplay should be managed via setting `autoplayFirstVideo`
Docs - https://sachinchoolur.github.io/lightgallery.js/docs/api.html#lg-video
