### ISSUE TITLE
Change video.js size

### ISSUE THREAD

**Issue by user9823749** [sachinchoolur/lightgallery.js#188]
Hi,
How i can change default video.js size when i click on video its open but is small i want 
min-width: 100%
to make it on full window and keep proportion.
I cannot find it on css file
Thank you

**Comment by sachinchoolur** [comment]
You can set `videoMaxWidth` : `none` to remove max width
https://sachinchoolur.github.io/lightgallery.js/docs/api.html#lg-video

**Comment by user9823749** [comment]
When i use that function its disables videojs player and controls like share download etc

**Comment by sachinchoolur** [comment]
If you set max-width none, it will occupy full space. 
You can set whatever max-width value based on your requirement 
For example,

    videoMaxWidth: 'calc(100% - 250px)';

**Comment by user9823749** [comment]
```
echo '          <script type="text/javascript">'
echo '                  $(document).ready(function() {'
echo '                          var $lg = $("body");'
echo '                          $lg.lightGallery({'
echo '                                  selector: ".lightbox-file",'
echo '                                  fullScreen: true,'
echo '                                  thumbnail: false,'
echo '                                  videojs: true,'
echo '                                  videoMaxWidth: 'calc(100% - 250px)';'
echo '                          });'
echo '                          $lg.on("onAfterOpen.lg", function(){'
echo '                                  $lg.data("lightGallery").modules.fullscreen.requestFullscreen();'
echo '                          });'
echo '                  });'
echo '          </script>'
```

when i add videoMaxWidth i dont have longer videojs player and got no top buttons its open trought regular browser player and i cant scroll it left right and no thumbnail
I want thumbnails video to be fullscreen and video as well without clicking on video play button.


![Screenshot_20210127-063831_Edge](https://user-images.githubusercontent.com/66221784/105953037-6dcec780-606a-11eb-8f46-e8b1625870c0.jpg)
![Screenshot_20210127-063753_Edge](https://user-images.githubusercontent.com/66221784/105953048-70312180-606a-11eb-93b5-23b025417c0b.jpg)

**Comment by sachinchoolur** [comment]
There is a syntax error in your code 

- videoMaxWidth: 'calc(100% - 250px)';'

please fix the issue and try again. 
If the issue persists, please provide a jsfiddle demo. I'll fix the issue and send it back to you

**Comment by user9823749** [comment]
```
echo '          <script type="text/javascript">'
echo '                  $(document).ready(function() {'
echo '                          var $lg = $("body");'
echo '                          $lg.lightGallery({'
echo '                                  selector: ".lightbox-file",'
echo '                                  fullScreen: true,'
echo '                                  thumbnail: false,'
echo '                                  videojs: true,'
echo '                                  videoMaxWidth: none,'
echo '                          });'
echo '                          $lg.on("onAfterOpen.lg", function(){'
echo '                                  $lg.data("lightGallery").modules.fullscreen.requestFullscreen();'
echo '                          });'
echo '                  });'
echo '          </script>'
```

still the same

**Comment by sachinchoolur** [comment]
Hey @user9823749 ,

Oh my bad. You need to add the following styles to your document. 

``` css
.lg-outer .lg-video {
    width: auto;
    height: auto;
    padding: 0;
    position: static;
}
```

Here is the demo = https://codepen.io/lightGallery/pen/PozdEyx
