### ISSUE TITLE
custom hash url

### ISSUE THREAD

**Issue by sograra** [sachinchoolur/lightgallery.js#189]
Hi Sachin, great plugin!

_How can I go about adding a custom hash to the current slide?_ I need to add a custom url which corresponds to the source url of the current image in the slide show.

I've tried adding a custom data attribute ( called data-source ) to the source where lightgallery grabs the source ( data-src ) but it look like lightgallery only copies the src and not the actual element so I can't grab the data-attribute to use with my event listener as such:

```html
<div 
class="portfolio-item"  
data-src="../url/to/image/that/lightgallery/use"  
data-sub-html="text which lightgallery uses>" 
data-source="../url/to/original/post/where/the/image/are/from">
```

```javascript
var lg = document.getElementById( 'portfolio' );

lightGallery( lg, {
  download: false
} );

lg.addEventListener( 'onAfterSlide', function( event ){
  var currentSlide = document.querySelector('.lg-current');
  console.log( currentSlide );
}, false);
```
Any help or suggestions would be greatly appreciated,
Sograra

**Comment by sachinchoolur** [comment]
Hey @sograra ,
Sorry for the delayed response.

The plugin instances are stored in lgData variable.

``` js

// Access data
pluginData = window.lgData[lg.getAttribute('lg-uid')];

// get data-source
lg.addEventListener( 'onAfterSlide', function( event ){
  const source =  pluginData.items[event.detail.index].getAttribute('data-source');
}, false);

```

If you are just looking for custom-hash for each slide, it is already done in v2 - https://github.com/sachinchoolur/lightGallery/blob/v2/src/plugins/hash/lg-hash.ts

V2 will be released once the documentation work is completed
