### ISSUE TITLE
weird visual bug.

### ISSUE THREAD

**Issue by picarica** [sachinchoolur/lightgallery.js#190]
so when i scroll on phone it seems that i have 3 pictures in my gallery, and when i move from first to second image the third image weirdly slides in teh background i uploaded the video so you can visualize it better.
this bug occurs in every browser, even on PC, i am using latest lightgallery.js aand this also happens without any options

https://www.youtube.com/watch?v=gh-WWcKSmvk&feature=youtu.be

**Comment by sachinchoolur** [comment]
Thanks for the video. There might be some css conflicts with your app. 
Could you please share your website url if available?
