### ISSUE TITLE
Help me >_< merge two gallery in one output

### ISSUE THREAD

**Issue by ZeoNish** [sachinchoolur/lightgallery.js#192]
![image](https://user-images.githubusercontent.com/8596319/107920372-eb0c9e80-6f7d-11eb-9278-1dead087d801.png)

Need merge 2 gallery in one output...

![image](https://user-images.githubusercontent.com/8596319/107920492-1d1e0080-6f7e-11eb-89c4-effd36151d24.png)

add gallery 1 

im use code 

require(["jquery", "lightgallery"], function () {
            require(["lg-thumbnail", "lg-fullscreen"], function () {

                lightGallery(document.getElementById("lightgallery"), {
                    selector: ".lg-item a"
                });

            });
   });

**Comment by ZeoNish** [comment]
help?

**Comment by sachinchoolur** [comment]
Hey @ZeoNish,

Yes, it is possible. Basically, you just need to set the proper `selector` property.
Could you please share your HTML markup?

**Comment by ZeoNish** [comment]
> Hey @ZeoNish,
> 
> Yes, it is possible. Basically, you just need to set the proper `selector` property.
> Could you please share your HTML markup?

`<div class="col-md-6">

    <div class="row">

        <div class="col-6 col-sm-6 col-lg-6">

            <div class="hr-text hr-text-center">
                Превью
            </div>

            <div class="card" id="card-poster-personal" lg-uid="lg1">

                <a class="full-img-poster d-block link-overlay"
                   href="/storage/uploads/pigeons/preview/55bb4a05d47960629510f2a0dc2fd08a.jpg">
                    <img class="card-img-top d-block img-fluid rounded "
                         src="/storage/uploads/pigeons/preview/55bb4a05d47960629510f2a0dc2fd08a.jpg" alt="">
                    <span class="link-overlay-bg rounded">
                        <i class="fe fe-eye"></i>
                    </span>
                </a>

                <script>
                    require(['jquery', 'lightgallery'], function () {
                        require(['lg-thumbnail', 'lg-fullscreen'], function () {

                            lightGallery(document.getElementById('card-poster-personal'), {
                                selector: 'a.full-img-poster'
                            });

                        });
                    });
                </script>


            </div>
        </div>


        <div class="col-6 col-sm-6 col-lg-6">

            <div class="hr-text hr-text-center">Фото</div>

            <div class="card no-border">
                <div class="card-body p-0">


                    <div id="lightgallery" class="row img-gallery" lg-uid="lg2">


                        <div class="col-4 lg-item">
                            <a href="/storage/uploads/pigeons/photos/ff64ff06730b364edebcf139a8271429.jpg"
                               class="d-block link-overlay">
                                <img class="d-block img-fluid rounded"
                                     src="/storage/uploads/pigeons/photos/ff64ff06730b364edebcf139a8271429.jpg" alt="">
                                <span class="link-overlay-bg rounded">
                                    <i class="fe fe-eye"></i>
                                </span>
                            </a>
                        </div>


                        <div class="col-4 lg-item">
                            <a href="/storage/uploads/pigeons/photos/ce18a6345e5f2dd87eb221bdeb564543.jpg"
                               class="d-block link-overlay">
                                <img class="d-block img-fluid rounded"
                                     src="/storage/uploads/pigeons/photos/ce18a6345e5f2dd87eb221bdeb564543.jpg" alt="">
                                <span class="link-overlay-bg rounded">
                                    <i class="fe fe-eye"></i>
                                </span>
                            </a>
                        </div>


                    </div>

                    <script>
                        require(['jquery', 'lightgallery'], function () {
                            require(['lg-thumbnail', 'lg-fullscreen'], function () {

                                lightGallery(document.getElementById('lightgallery'), {
                                    selector: '.lg-item a'
                                });

                            });
                        });
                    </script>

                </div>
            </div>
        </div>
    </div>
</div>`

**Comment by sachinchoolur** [comment]
Thank you for providing the details 

``` html
<div class="row">

    <div class="col-6 col-sm-6 col-lg-6">

        <div class="hr-text hr-text-center">
            Превью
        </div>

        <div class="card" id="card-poster-personal" lg-uid="lg1">

            <a class="full-img-poster d-block link-overlay gallery-item"
               href="/storage/uploads/pigeons/preview/55bb4a05d47960629510f2a0dc2fd08a.jpg">
                <img class="card-img-top d-block img-fluid rounded "
                     src="/storage/uploads/pigeons/preview/55bb4a05d47960629510f2a0dc2fd08a.jpg" alt="">
                <span class="link-overlay-bg rounded">
                    <i class="fe fe-eye"></i>
                </span>
            </a>
        </div>
    </div>


    <div class="col-6 col-sm-6 col-lg-6">

        <div class="hr-text hr-text-center">Фото</div>

        <div class="card no-border">
            <div class="card-body p-0">


                <div id="lightgallery" class="row img-gallery" lg-uid="lg2">


                    <div class="col-4 lg-item">
                        <a class="gallery-item" href="/storage/uploads/pigeons/photos/ff64ff06730b364edebcf139a8271429.jpg"
                           class="d-block link-overlay">
                            <img class="d-block img-fluid rounded"
                                 src="/storage/uploads/pigeons/photos/ff64ff06730b364edebcf139a8271429.jpg" alt="">
                            <span class="link-overlay-bg rounded">
                                <i class="fe fe-eye"></i>
                            </span>
                        </a>
                    </div>


                    <div class="col-4 lg-item">
                        <a class="gallery-item" href="/storage/uploads/pigeons/photos/ce18a6345e5f2dd87eb221bdeb564543.jpg"
                           class="d-block link-overlay">
                            <img class="d-block img-fluid rounded"
                                 src="/storage/uploads/pigeons/photos/ce18a6345e5f2dd87eb221bdeb564543.jpg" alt="">
                            <span class="link-overlay-bg rounded">
                                <i class="fe fe-eye"></i>
                            </span>
                        </a>
                    </div>


                </div>

                <script>
                    require(['jquery', 'lightgallery'], function () {
                        require(['lg-thumbnail', 'lg-fullscreen'], function () {

                            lightGallery(document.getElementById('lightgallery'), {
                                selector: '.gallery-item',
                               selectWithin: 'body'
                            });

                        });
                    });
                </script>

            </div>
        </div>
    </div>
</div>
```

Please try with the updated HTML.
I made some modifications 
- Added `.gallery-item`class name to all gallery items including both galleries 
- Removed duplicate initialization of lightGallery (You don't have to create two galleries)
- Added `selectWithin` property. 

Please let me know if this works for you

**Comment by ZeoNish** [comment]
> Thank you for providing the details
> 
> ```
> <div class="row">
> 
>     <div class="col-6 col-sm-6 col-lg-6">
> 
>         <div class="hr-text hr-text-center">
>             Превью
>         </div>
> 
>         <div class="card" id="card-poster-personal" lg-uid="lg1">
> 
>             <a class="full-img-poster d-block link-overlay gallery-item"
>                href="/storage/uploads/pigeons/preview/55bb4a05d47960629510f2a0dc2fd08a.jpg">
>                 <img class="card-img-top d-block img-fluid rounded "
>                      src="/storage/uploads/pigeons/preview/55bb4a05d47960629510f2a0dc2fd08a.jpg" alt="">
>                 <span class="link-overlay-bg rounded">
>                     <i class="fe fe-eye"></i>
>                 </span>
>             </a>
>         </div>
>     </div>
> 
> 
>     <div class="col-6 col-sm-6 col-lg-6">
> 
>         <div class="hr-text hr-text-center">Фото</div>
> 
>         <div class="card no-border">
>             <div class="card-body p-0">
> 
> 
>                 <div id="lightgallery" class="row img-gallery" lg-uid="lg2">
> 
> 
>                     <div class="col-4 lg-item">
>                         <a class="gallery-item" href="/storage/uploads/pigeons/photos/ff64ff06730b364edebcf139a8271429.jpg"
>                            class="d-block link-overlay">
>                             <img class="d-block img-fluid rounded"
>                                  src="/storage/uploads/pigeons/photos/ff64ff06730b364edebcf139a8271429.jpg" alt="">
>                             <span class="link-overlay-bg rounded">
>                                 <i class="fe fe-eye"></i>
>                             </span>
>                         </a>
>                     </div>
> 
> 
>                     <div class="col-4 lg-item">
>                         <a class="gallery-item" href="/storage/uploads/pigeons/photos/ce18a6345e5f2dd87eb221bdeb564543.jpg"
>                            class="d-block link-overlay">
>                             <img class="d-block img-fluid rounded"
>                                  src="/storage/uploads/pigeons/photos/ce18a6345e5f2dd87eb221bdeb564543.jpg" alt="">
>                             <span class="link-overlay-bg rounded">
>                                 <i class="fe fe-eye"></i>
>                             </span>
>                         </a>
>                     </div>
> 
> 
>                 </div>
> 
>                 <script>
>                     require(['jquery', 'lightgallery'], function () {
>                         require(['lg-thumbnail', 'lg-fullscreen'], function () {
> 
>                             lightGallery(document.getElementById('lightgallery'), {
>                                 selector: '.gallery-item',
>                                selectWithin: 'body'
>                             });
> 
>                         });
>                     });
>                 </script>
> 
>             </div>
>         </div>
>     </div>
> </div>
> ```
> 
> Please try with the updated HTML.
> I made some modifications
> 
> * Added `.gallery-item`class name to all gallery items including both galleries
> * Removed duplicate initialization of lightGallery (You don't have to create two galleries)
> * Added `selectWithin` property.
> 
> Please let me know if this works for you

Thank you so much for your help !!!
