### ISSUE TITLE
Images not presenting itself correctly on ipad

### ISSUE THREAD

**Issue by DonaldB381** [sachinchoolur/lightgallery.js#194]
I've set up a gallery to open dynamically and it works fine on a computer but when it runs on an ipad it seems quite buggy. I can't figure out why this is. 

What happens is that it goes through the loading process and then displays the image but it is only a partial area of the image from the top down (see attached). It sometimes loads some properly but consistantly some are not and only showing partial images. The website page is (www.pleasantjourney.net/journeys.html). Could someone suggest something please? I can't figure out thus one and I'm a bit new to this javascript. It's all been set up properly as far as I know.

Cheers!
![IMG_0001](https://user-images.githubusercontent.com/79860416/109525566-8e46d300-7aa9-11eb-82f1-9bfd80574ac4.JPG)
![IMG_0004](https://user-images.githubusercontent.com/79860416/109525572-8f780000-7aa9-11eb-8e2c-d6ff970debfe.JPG)

**Comment by justOtto** [comment]
On my iPad (using Safari) Pictures are perfectly loading, except the first from France. After swiping through all France Images the first was also loaded. Couldn't reproduce the issue.
But the menu also didn't work at the beginning, had to type in the path (journeys.html) manually. After watching your photos (i really like the venice pictures btw. :-) the menu was perfectly working and i also couldn't reproduce the issue.
Didn't inspect your website any further but seems not to be a lightgallery problem to me.
