### ISSUE TITLE
How to load plugins

### ISSUE THREAD

**Issue by ddrury** [sachinchoolur/lightgallery.js#203]
Using npm to load lightgallery.js 1.4.1-beta.0, the node package doesn't contain any plugins

**Comment by sachinchoolur** [comment]
You need to install plugins separately - https://github.com/sachinchoolur/lightgallery.js#built-in-modules

If you are using v2, plugins are available within the same package - http://sachinchoolur.github.io/lightGallery/v2/docs/getting-started/#include-css-and-javascript-files

**Comment by ddrury** [comment]
Wow, that was fast - thanks.

I'm having a problem with v2 at the moment. I'm using laravel webpack.mix and I keep getting lightGallery is undefined. I think it must be something to do with the way I'm combining all the js

**Comment by sachinchoolur** [comment]
OK. Let me know if you have any questions.

You can take a look at the codepen demos if you need.
https://codepen.io/sachinchoolur/pen/qBrbbNQ
ES6 imports - https://codepen.io/sachinchoolur/pen/qBrbbNQ
