### ISSUE TITLE
upgrade to v2 banner has broken link

### ISSUE THREAD

**Issue by evanwill** [sachinchoolur/lightgallery.js#204]
The alert banner on top of <https://sachinchoolur.github.io/lightgallery.js/>

says "upgrade to version 2" with link <http://lightgalleryjs.com/>

That link directs to a GoDaddy domain "parked free" page. 
It seems like the correct link should be <https://www.lightgalleryjs.com/> instead.

Thank you!

**Comment by sachinchoolur** [comment]
Thank you for pointing this out. Sometimes redirection is not happening properly.

I've updated the links
