### ISSUE TITLE
Lazyload thumbnails

### ISSUE THREAD

**Issue by alvinkonda** [sachinchoolur/lightgallery.js#205]
I'm using the dynamic mode, but it seems the thumbnails are not lazyloaded, which has caused the page size to be 25Mb. I have several gallery instances on the same page, and yes, I'm using the full image as the thumbnail.

**Comment by wwwonka** [comment]
Hey @alvinkonda,
Just passing by.
This is not a built-in solution but by using [progressive-image.js](https://github.com/craigbuckler/progressive-image.js) in combination with lightgallery, you can lazy-load the thumbnails on your page while having something quite good-looking to show to your users during that time.

I am myself doing this for my current project and this is the markup that has been working for me:


 ```
 <template id="gallery-item">
                <a href="img-thumb.jpg" class="progressive replace" data-src="img.jpg" data-lg-size="3000-3000">
                    <img src="img-tiny.jpg" class="main-gallery-img preview" onload="this.style.opacity=1">
                </a>
 </template>
```

Taught this was worth sharing for you and in case  @sachinchoolur collects ideas for future plugins... 🙃.

Cheers 🖖.

**Comment by wwwonka** [comment]
Hey @alvinkonda,
Just passing by.
This is not a built-in solution but by using lightgallery in combination with [progressive-image.js](https://github.com/craigbuckler/progressive-image.js), you may automatically lazy-load the thumbnails on your page, all while having something quite good-looking on display while users are waiting. [See](https://codepen.io/craigbuckler/full/yPqLXW).

For  [780 bytes](https://bundlephobia.com/package/progressive-image.js@1.6.0) added to your build, it's a pretty good deal all things considered.

My current project uses v2, so it might differ for you, but here's the markup that has been working for me:


 ```
<template id="gallery-item">
    <a href="img-thumb.jpg" class="progressive replace" data-src="img-full.jpg" data-lg-size="3000-3000">
        <img src="img-tiny.jpg" class="main-gallery-img preview" onload="this.style.opacity=1">
    </a>
</template>
```

Taught this was worth sharing and in case @sachinchoolur is listening, collecting ideas for future plugins...!

Cheers 🖖.
