### ISSUE TITLE
Init on reach structure

### ISSUE THREAD

**Issue by sashabeep** [sachinchoolur/lightgallery.js#210]
I have pretty complex layout of my thumbnails with different element structure - columns, rows, etc. Packed in slides.

How to init gallery for all the images on all the slides with prev/next functionality on all the media? 

![Снимок экрана 2021-08-31 в 18 42 06](https://user-images.githubusercontent.com/5689796/131537072-1cd256c2-47de-4ba0-ab4f-f897d3a038f4.png)

For now i have only one working example - init on each thumbnail link using
```js
var elements = document.getElementsByClassName('boatmedia-item'); //link to the image
	for (let item of elements) {
		lightGallery(item, {
			licenseKey: 'D...0',
			speed: 500,
			download: false,
  			share: false
		})
	}
```

But in this case i have only 1/1 slide index always (btw, why lightbox is so small? how to expand it as much as possible?)
![Снимок экрана 2021-08-31 в 19 06 11](https://user-images.githubusercontent.com/5689796/131537551-49fcfb32-8014-40ef-9efb-edde20e31714.png)

PLUS
Some of thumbnails should have link to youtube video/embed or something

**Comment by sachinchoolur** [comment]
Hey @sashabeep,

You can apply lightGallery to any parent container specify the slideITems by using the selector option


```js
lightGallery(document.body, {
			licenseKey: 'D...0',
                         selector: 'boatmedia-item a'
			speed: 500,
			download: false,
  			share: false
		})
```

if you can share the HTML structure, I can provide you the exact selector

**Comment by sashabeep** [comment]
@sachinchoolur Thanks, solved using selector
