### ISSUE TITLE
Captions / Title not taking correct height

### ISSUE THREAD

**Issue by niklasp** [sachinchoolur/lightgallery.js#211]
When the first image I open only has a title and no caption and the others have, the height is not calculated correclty. Only works if all images have title and caption of same height.
<img width="1069" alt="Bildschirmfoto 2021-09-27 um 14 57 30" src="https://user-images.githubusercontent.com/1685139/134912617-80ba6082-7e26-42ec-9de3-28559e1c997b.png">
.

**Comment by sachinchoolur** [comment]
Setting different heights for images would cause a poor transition experience. That is the reason why it is stable for all slides.
Can you try setting an appropriate `defaultCaptionHeight ` value? If it doesn't work well, I'll consider setting different caption heights for each slide.

Also, going forward pls post issues in https://github.com/sachinchoolur/lightGallery as this repo is no longer maintained
