### ISSUE TITLE
How to use lightgallery/vue with Vue display HTML5 video?

### ISSUE THREAD

**Issue by gago8910** [sachinchoolur/lightgallery.js#212]

**Comment by sachinchoolur** [comment]
Hey @gago8910,

Sorry for the late reply. this repo is no longer maintained. Going forward, please use https://github.com/sachinchoolur/lightGallery instead

Here is the demo  of HTML5 video with vue  (last slide)- https://stackblitz.com/edit/lightgallery-vue?file=src%2FApp.vue
