### ISSUE TITLE
Missing few images in main page

### ISSUE THREAD

**Issue by jignesh6990** [sachinchoolur/lightgallery.js#216]
I have integrated lightgallery as described in demo. There are total 9 photos I have added in html code. When I view the gallery it display 8 photos. While clicking on any image it display the popup and it loads all 9 thumbnail images. 

![1](https://user-images.githubusercontent.com/4235471/156911173-0a6a9bfe-d442-43fe-9d62-14d4f9931eef.png)
![2](https://user-images.githubusercontent.com/4235471/156911176-263b828e-f090-46a0-981a-c121e26df82d.png)

Below is the html which I have used.
https://docs.google.com/document/d/1Sf2N10scHVa4H6t3uiZVXMIAy1gOwRX65movGt6JckU/edit?usp=sharing

Thanks,
JP

**Comment by ahmadjubair33** [comment]
Hi @jignesh6990 Can you tell me in which branch your code is present.Thank you

**Comment by jignesh6990** [comment]
> Hi @jignesh6990 Can you tell me in which branch your code is present.Thank you

You can use this repository for code files. https://github.com/jignesh6990/lgdemo

I want to integrate LG to display photos. I have followed the demo code.

Thank you,
JP
