### ISSUE TITLE
Importing to React

### ISSUE THREAD

**Issue by yankeyhotel** [sachinchoolur/lightgallery.js#25]
I am trying to import this into React. I keep getting an empty object. I am not sure if I am doing it incorrectly or if there is an issue.

```
import lightGallery from 'lightgallery.js';
console.log(lightGallery); // returns Object {}
```

thanks

**Comment by sachinchoolur** [comment]
I think the following code should work

``` Javascript
import 'lightgallery.js';
console.log(lightGallery); 
```

**Comment by iweb-wiki** [comment]
Is your problem solved?

**Comment by Halkyon64** [comment]
has anyone solved this problem? I'm using import statemant as intended, but get nothing.
How can i use this wonderfull plugin with React.js?

thanks!

**Comment by Halkyon64** [comment]
see answer here https://stackoverflow.com/questions/49232497/how-to-use-lightgallery-with-react-js

p.s.
@sachinchoolur thank you for plagin, it works great!

**Comment by schmitt-kevin** [comment]
> see answer here https://stackoverflow.com/questions/49232497/how-to-use-lightgallery-with-react-js
> 
> p.s.
> @sachinchoolur thank you for plagin, it works great!

This is for lightgallery. There is a difference between lightgallery.js and lightgallery. One doesn't require jquery

**Comment by schmitt-kevin** [comment]
I'm still unable to import and use lightgallery.js with react
