### ISSUE TITLE
Each image is counted as a page

### ISSUE THREAD

**Issue by PatrickdeBie** [sachinchoolur/lightgallery.js#26]
- Open demo page https://sachinchoolur.github.io/lightgallery.js/
- Click on first image (flower).
- Click on right arrow on screen and wander through images
- Press back button of browser (Chrome in my case)
- Page does not return to previous page, but url changes to previous image and so on.

**Comment by sachinchoolur** [comment]
Hi,
This is a feature of lightgallery.js.  :smiley:
If you don't want to use just remove hash plugin from your document or pass `hash:false` via settings
