### ISSUE TITLE
Mixed content warnings for gh-pages

### ISSUE THREAD

**Issue by XhmikosR** [sachinchoolur/lightgallery.js#3]
I tried to fix it myself but I can't checkout the gh-pages branch on Windows.

``` shell
xmr@xmr-PC ~
$ cd /c/Users/xmr/Desktop/lightgallery.js/

xmr@xmr-PC /c/Users/xmr/Desktop/lightgallery.js
$ git checkout -b gh-pages remotes/origin/gh-pages
fatal: cannot create directory at 'lightgallery/sass/C:': Invalid argument
```

The fix should be pretty easy; just use `https` for all `link`s and `script`s.

**Comment by XhmikosR** [comment]
@sachinchoolur: can you remove `gh-pages/lightgallery/sass/C:` from the repo?

**Comment by sachinchoolur** [comment]
Hi @XhmikosR ,
Thank you. I've removed the css file.

**Comment by XhmikosR** [comment]
Weird I still can't check out the gh-pages branch...

**Comment by XhmikosR** [comment]
There's still one instance, in less folder.

**Comment by XhmikosR** [comment]
So, can you remove that file too?

**Comment by sachinchoolur** [comment]
Yes, I will do it by tomorrow morning(IST).
Thank you so much for your contributions so far.

**Comment by sachinchoolur** [comment]
Hi,
I have fixed the issues..

**Comment by XhmikosR** [comment]
There's still an issue with Twitter. Just search for `http`, exact match and review the results.

**Comment by sachinchoolur** [comment]
It is generated by sharrre plugin :disappointed:
