### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of null

### ISSUE THREAD

**Issue by Calinou** [sachinchoolur/lightgallery.js#30]
I'm setting up lightgallery.js for a website and am running into an issue with it using version 0.0.3.

The error message is:

```
Uncaught TypeError: Cannot read property 'match' of null
```

Running the non-minified script fails at line 638, which contains:

``` js
var youtube = src.match(/\/\/(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=|embed\/)?([a-z0-9\-\_\%]+)/i);
```

Here's the relevant markup (which uses the Pure CSS framework):

``` html
<section class="content">
  <h1 class="text-centered">Gallery</h1>
  <div id="lightgallery" class="pure-g">
    <div class="pure-u-1 pure-u-sm-1-2">
      <a href="/media/gallery/1.jpg">
        <img src="/media/gallery/1.jpg" class="pure-img">
      </a>
    </div>
    <div class="pure-u-1 pure-u-sm-1-2">
      <a href="/media/gallery/2.jpg">
        <img src="/media/gallery/2.jpg" class="pure-img" >
      </a>
    </div>
    <div class="pure-u-1 pure-u-sm-1-2">
      <a href="/media/gallery/3.jpg">
        <img src="/media/gallery/3.jpg" class="pure-img" >
      </a>
    </div>
    <div class="pure-u-1 pure-u-sm-1-2">
      <a href="/media/gallery/4.jpg">
        <img src="/media/gallery/4.jpg" class="pure-img" >
      </a>
    </div>
  </div>
</section>
```

And the JavaScript used to initialize it:

``` html
<script src="/assets/js/lightgallery.js"></script>
<script>
  lightGallery(document.getElementById('lightgallery'));
</script>
```

I'm not using any other JavaScript files on that site, not even jQuery. Note that it used to work for a small while, but I can't remember why.

I can reproduce this behavior with both Chromium 52 and Firefox 48.

**Comment by Calinou** [comment]
Solved: the `<div class="pure-u-1 pure-u-sm-1-2">` tags need a `data-src=/media/gallery/x.jpg` attribute in order to work.

**Comment by bramus** [comment]
Also ran into this issue. It is fixable indeed _(as mentioned above)_ by adding some extra markup, yet it should not occur in the first place I think.

Can you reopen this @Calinou / @sachinchoolur ?

**Comment by marcobiedermann** [comment]
This issue is that the anchor (`data-src`) must be a direct sibling of the element which is being initialized.

**Comment by kapilSoni101** [comment]
anybody fixed above issue?

**Comment by bramus** [comment]
@kapilSoni101 See @Calinou's workaround above.

**Comment by sachinchoolur** [comment]
Hey guys,

In case if you are using custom HTML markup, you need to use the selector property. 
Demo - https://sachinchoolur.github.io/lightgallery.js/demos/html-markup.html

For example in the for the bellow HTML markup, instead of changing data-src, you can just pass `a` tag as selector


``` html 

<section class="content">
  <h1 class="text-centered">Gallery</h1>
  <div id="lightgallery" class="pure-g">
    <div class="pure-u-1 pure-u-sm-1-2">
      <a href="/media/gallery/1.jpg">
        <img src="/media/gallery/1.jpg" class="pure-img">
      </a>
    </div>
    <div class="pure-u-1 pure-u-sm-1-2">
      <a href="/media/gallery/2.jpg">
        <img src="/media/gallery/2.jpg" class="pure-img" >
      </a>
    </div>
    <div class="pure-u-1 pure-u-sm-1-2">
      <a href="/media/gallery/3.jpg">
        <img src="/media/gallery/3.jpg" class="pure-img" >
      </a>
    </div>
    <div class="pure-u-1 pure-u-sm-1-2">
      <a href="/media/gallery/4.jpg">
        <img src="/media/gallery/4.jpg" class="pure-img" >
      </a>
    </div>
  </div>
</section>
```
``` js
lightGallery(document.getElementById('lightgallery'), {
    selector: 'a' 
});
```
