### ISSUE TITLE
Hover titles on the icons

### ISSUE THREAD

**Issue by wschwaiger** [sachinchoolur/lightgallery.js#31]
Hi,

First of all great implementation! What I am missing is a hover title on the icons. A title which describes what the click on the icons will do.

Thanks. Keep up the great work,
Wolfgang

**Comment by rgejji** [comment]
I would also like to see tooltip support, or hover over titles on the icons. Some of them are not completely intuitive.

It could be something as simple as download when over the download icon, fullscreen over the fullscreen icon, etc. Or these could be optional variables which the app developer can write in.
