### ISSUE TITLE
Can not set index when open gallery on the second time or later

### ISSUE THREAD

**Issue by ccqgithub** [sachinchoolur/lightgallery.js#34]
and, i must do like this:

```
var obj = window.lgData[this.refs.lightgallery.getAttribute('lg-uid')];

 // fix index bug
  if (obj) obj.s.index = index;
```

**Comment by httpster** [comment]
I am experiencing this same issue. It's almost like it's caching the initial index setting.

**Comment by dbaida** [comment]
It seems that the issue is still there. Do you have any update regarding the issue?

**Comment by djbobbydrake** [comment]
Confirming that issue is still there.
