### ISSUE TITLE
justifyedGallery alternatives

### ISSUE THREAD

**Issue by AlessandroAnnini** [sachinchoolur/lightgallery.js#38]
Hi,
sorry, this is not completely about lightgallery.js but i think i can have an answer here..

i am trying to implement lightgallery.js in a React.js project and i like the way justifiedGallery arrange the photos but i cannot use it with react because it is a jQuery plugin.
Did someone found an alternative that can be used for the lightgallery.js markup structure without jQuery needed?
Thank you!

**Comment by AlessandroAnnini** [comment]
I ended up using Flexbox layout. You can archive almost the same result an be cleaner..

**Comment by nk9** [comment]
Do you have an example of this? I'm not sure how to get the individual items to resize and also enforce justification with just CSS…

**Comment by nk9** [comment]
I found [this example](https://github.com/xieranmaya/blog/issues/6) linked from StackOverflow.
