### ISSUE TITLE
lg-slide animation is working incorrectly with 2 images

### ISSUE THREAD

**Issue by danii1** [sachinchoolur/lightgallery.js#45]
If there are only 2 images in gallery, they slide to the wrong side

**Comment by gvdlangenberg** [comment]
This still seems to be a problem..

**Comment by adrienlamotte** [comment]
Hello,
I have the same issue here with the last version of lightgallery... Does anyone has an idea on how to fix this ?

**Comment by bupy7** [comment]
The same problem. I just disabled its by using `mode => none`, because the other effects didn't fit for me. =)
