### ISSUE TITLE
Pinch to Zoom

### ISSUE THREAD

**Issue by northkode** [sachinchoolur/lightgallery.js#46]
Not so much an issue then a question. 
Does this support pinch to zoom vs just the button click?

**Comment by MRZMUH001** [comment]
Hi @sachinchoolur - Are there any plans to implement Pinch to Zoom in lightGallery.js?

I see you have a planned release in the jQuery version. https://github.com/sachinchoolur/lightGallery/issues/211

**Comment by mariomurrent-softwaresolutions** [comment]
Any plans for 2.0? Pinch would be really awesome
