### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mtimiso** [sachinchoolur/lightgallery.js#48]
What is the difference between this plugin which is licensed under Apache 2.0 and free for commercial use and the other one called "lightGallery" which requires purchase of a commercial license? 

The plugins are identical, why is one free and one not?

Free version:
https://sachinchoolur.github.io/lightgallery.js/

Paid version:
http://sachinchoolur.github.io/lightGallery/

**Comment by sachinchoolur** [comment]
https://github.com/sachinchoolur/lightGallery/issues/463
