### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by AlessandroAnnini** [sachinchoolur/lightgallery.js#5]
This is just a proposal but what about lazy loading?
thanks!

**Comment by Galothus** [comment]
Examples that are in the website load one neighbouring image from both sides of the one you are currently viewing ( unless the image is first on the list -> right one will be loaded OR you click the last image skipping some inbetween -> left one will be loaded).

**Comment by sachinchoolur** [comment]
Hi Guys,
You can also configure the number of preload images via settings. 
Docs -https://sachinchoolur.github.io/lightgallery.js/docs/api.html

**Comment by AlessandroAnnini** [comment]
thanks @sachinchoolur, is this possible with thumbnails gallery too?
