### ISSUE TITLE
containing gallery inside an element

### ISSUE THREAD

**Issue by guykatz** [sachinchoolur/lightgallery.js#52]
Hi;
I want to use the fixed dims gallery as a kind of a carousel (https://sachinchoolur.github.io/lightgallery.js/demos/fixed-size.html)
however, I want the carousel to be contained inside a specific element of my choice. looking at this code it looks like no matter what there is a full size overlay in the back ground that is 'not containable'
is there a way to achieve what i need?
for example, my website has a header that I do not want to cover with the gallery overlay. but I would just like it to not overflow from the element I want it to be in.
thanks!

**Comment by sachinchoolur** [comment]
https://github.com/sachinchoolur/lightGallery/issues/499
