### ISSUE TITLE
Woff2 support for the font

### ISSUE THREAD

**Issue by stof** [sachinchoolur/lightgallery.js#53]
It would be great if the custom font could be provided in woff2 format as well, as it is supported by most browsers and is more efficient than woff (and so should be the preferred format for supporting browsers)

**Comment by S1SYPHOS** [comment]
![](http://i0.kym-cdn.com/entries/icons/original/000/016/042/Wait-For-It.jpg)

**Comment by S1SYPHOS** [comment]
There it is :cake:

**Comment by bramus** [comment]
Could this be merged? I think it will solve https://github.com/sachinchoolur/lightgallery.js/issues/96 too.

**Comment by stof** [comment]
@bramus no, it won't

**Comment by S1SYPHOS** [comment]
It should be merged - simple as that :/

**Comment by sachinchoolur** [comment]
Hey @S1SYPHOS,

Sorry for not responding on time. lightGallery version 2 release is planned for this week. So I'm trying to clean up all the old issues.
Yes, this needs to be updated. I'll update the fonts ASAP. (I need to create a premium account on icomoon)

**Comment by S1SYPHOS** [comment]
You do? Well, thanks for replying anyway - and for providing you his great library. Looking forward to v2!

**Comment by sachinchoolur** [comment]
Yes, https://github.com/sachinchoolur/lightgallery.js/pull/87 already has conflicts. So I thought it is not fair to ask you to resolve it :( But, would really appreciate it if you could make a new PR for [v2](https://github.com/sachinchoolur/lightGallery/tree/v2) or update the old one.

**Comment by S1SYPHOS** [comment]
@sachinchoolur I'll look into it :fox_face:

**Comment by S1SYPHOS** [comment]
Might as well close this issue.

**Comment by sachinchoolur** [comment]
Yes, Closing as it is already merged
