### ISSUE TITLE
Prefer data-src attribute instead href (iframe links)

### ISSUE THREAD

**Issue by rolandtoth** [sachinchoolur/lightgallery.js#54]
I have added a google maps lightbox on a page and it works fine, using either the "href" and "data-src" attributes.

However, when I add both of them the "href" seems to be stronger. This is an issue because I would like to

- single click: open the map in a lightbox (using "data-src" with the embed link)
- middle click: open the google maps page (using "href" with the normal link)

When both attributes are present, middle click works fine (uses the "href" value), but single click also uses "href" data instead "data-src".

Is there a way I can force this behaviour or is there a workaround? My best guess is to use "noscript" tag but that's ugly.

**Comment by klihelp** [comment]
I was looking for this too.

@sachinchoolur Just swap the order preference:
`        _src = _this.items[index].getAttribute('href') || _this.items[index].getAttribute('data-src');`

**Comment by klihelp** [comment]
related https://github.com/sachinchoolur/lightGallery/issues/767
