### ISSUE TITLE
All Html5 videos plays at the same time when without poster

### ISSUE THREAD

**Issue by swiderski** [sachinchoolur/lightgallery.js#55]
If you take your demo for HTML5 videos http://sachinchoolur.github.io/lightGallery/demos/html5-videos.html and remove `data-poster` from each video, then when you click on item it will start autoplay of video.

 I know that it is planned that video without poster starts to play, but it start to play all videos that doesn't have poster :-)

With kind regards.

**Comment by Livijn** [comment]
This is still happening 2 years after issue was opened...

**Comment by sachinchoolur** [comment]
Really sorry for the delayed response. The issue was fixed in the jQuery version 3 years ago. But somehow I missed it in the vanilla js version.

The issue has been fixed in the vanilla version as well

Thank you for your patience
