### ISSUE TITLE
sass files in npm version

### ISSUE THREAD

**Issue by Painatalman** [sachinchoolur/lightgallery.js#6]
Hello. This is just a suggestion, but I've installed the npm version of your plugin and I've been loving it, so far. 

I'd just like to inquire about the possibility of adding the sass files to it, rather than just the lib and dist files.

Thank you very much for your attention, and please keep up the great work!

**Comment by sachinchoolur** [comment]
Hi @Painatalman,
I have includes SCSS files in version 0.0.2. Plase check
