### ISSUE TITLE
Vimeo Javascript

### ISSUE THREAD

**Issue by asha23** [sachinchoolur/lightgallery.js#65]
This should be updated to use the new Vimeo javascript API and not Froogaloop as it's deprecated now. The new player API is far better.

Any idea if this is going to happen? Or is this project now dead? There haven't been any commits in a good long time.

**Comment by sachinchoolur** [comment]
Hey @asha23,
Thank you for the information. I'll include the changes in lightGallery v 2.0 (Working on it). 
jQuery version of [lightGallery](https://github.com/sachinchoolur/lightGallery) is more maintained as it has more users than the JS version
