### ISSUE TITLE
util.js window & document getAttribute/setAttribute not working with google maps streetview

### ISSUE THREAD

**Issue by philipp-winterle** [sachinchoolur/lightgallery.js#67]
Problem
If you are using lightgallery.js with google maps on the same page (both libraries included) and want to use Google Maps Street View you will not be able to, because the lightgallery hardcoded functions for "getAttribute" and "setAttribute" on window and document will conflict with Google Maps Street View

Request
Remove these functions from window and document and use a util function instead.

Pull Request already added to #68

**Comment by 4skinSkywalker** [comment]
Same problem here. Please resolve

**Comment by philipp-winterle** [comment]
I guess the maintainer is not interested in PRs. Sadly

**Comment by bio** [comment]
I got the same issue. Please review PR.

**Comment by sophielevens** [comment]
Thanks for the solution @hummal. 

Is there a reason that this hasn't been reviewed or merged? This is a blocker for us and we would really appreciate it, we are reliant on this plugin working alongside Google maps. 

Thanks!

**Comment by sachinchoolur** [comment]
Guys,
The issue has been fixed. Sorry for the delay.
@hummal Thank you for the PR
