### ISSUE TITLE
lg-share id twice on the example page

### ISSUE THREAD

**Issue by kucsatax** [sachinchoolur/lightgallery.js#7]
div with id lg-share is not a good example, becuse you use lg-share id on the tollbar icons, and therefore the share button toggle functionality crushed... i spent 2 hours with the gallery when i realised that the problem is the two same id :) Sorry for my english.
https://sachinchoolur.github.io/lightgallery.js/demos/share.html

**Comment by sachinchoolur** [comment]
Hi,
Thank you for reporting this issue. I've fixed it.

**Comment by naumantabbsum** [comment]
Hi
i need little help on this issue let me know if you can! i shall be very thank full to you!
![error](https://cloud.githubusercontent.com/assets/1769752/17907606/2d552d7c-6996-11e6-80a8-75c563014b21.png)
