### ISSUE TITLE
Issue with importing lg-utils

### ISSUE THREAD

**Issue by jacquesdev** [sachinchoolur/lightgallery.js#70]
When I try to load this plugin, I get

`Uncaught SyntaxError: Unexpected token import`

And it stems from this line.
`import utils from './lg-utils';`

Any ideas why that would be?

It does work if I don't import the file?

**Comment by sachinchoolur** [comment]
Hey @jacquesdev,

Please use files in the dist folder and try again. https://github.com/sachinchoolur/lightgallery.js/tree/master/dist/js

Let me know if the issue persists

**Comment by jacquesdev** [comment]
Thanks @sachinchoolur, that did the trick.
