### ISSUE TITLE
Thumbnails urls are undefined when using only one tag for the structure

### ISSUE THREAD

**Issue by Robouste** [sachinchoolur/lightgallery.js#73]
Hello, 

Here is my html structure : 

`<img src="{{ smallPath }}" data-src="{{ fullPath }}" class="gallery-photo" />`

The lightgallery is firing correctly but all thumbnails are broken. When I check the sources, `src` is set to `undefined`. I guess it's because of the structure but I unfortunately can't change it :( 

Is there an attribute to set to get the current src of the image for the thumbnail ?

The gallery is working fine when using a two level structure (img inside anchor with href attribute)

**Comment by vesper8** [comment]
did you ever figure this out @Robouste ?

I have the same problem
