### ISSUE TITLE
use with hexo-themes, gallery layout not showing up

### ISSUE THREAD

**Issue by cutelittleturtle** [sachinchoolur/lightgallery.js#74]
Hi I have a naive question but I did not see any answers so I m going to ask it.

How do you implement this gallery with an existing hexo-theme? I am using a [hexo version of this plugin](https://github.com/lzane/hexo-light-gallery), which basically add the <head>, <script> and lightgallery call sections to all posts/pages. So all you need to do is to include image paths.

After installation, I can see the lightgallery zoom-in function running, but I do not see the gallery layout showing up. And the zoom-in part overlays with hexo's default zoom-in (i tried two different themes).

Details:

Hi, I want to use this gallery plugin on  my hexo blog. But the function seems to OVERLAY with the HEXO default image displaying. 

For example, I included 3 images `img1.jpg img2.jpg img3.jpm` in the post. When the site is served, I did not see a gallery, just 3 individual pictures. But when you click on the picture, you can see the lightgallery zoom-in window overlay with the default zoom-in window.

Is there a way to fix that?

theme: hexo-next, hexo-lanscape

_config.yml: 
`lightgallery:
               # all options comment-out/no plugin`

in post (asset_folder true):
`  <div id="gallery">
`
`    {% asset_img img1.jpg img1 %}
`
`    {% asset_img img2.jpg img2 %}
`
`    {% asset_img img3.jpg img3 %}
`   
` </div>

Check: 
css, script, .js are all present in page's source file.

Result:
no gallery:
![image](https://user-images.githubusercontent.com/31291893/30837185-d2208be6-a228-11e7-8901-fb42aea97139.png)

first layer of zoom-in (default)
![image](https://user-images.githubusercontent.com/31291893/30837189-d61d21d2-a228-11e7-856e-37b07f18e3a3.png)

second layer of zoom-in (lightgallery)
![image](https://user-images.githubusercontent.com/31291893/30837192-d8e51b5e-a228-11e7-81e3-8afcdd30057f.png)

**Comment by sachinchoolur** [comment]
Hay @cutelittleturtle,
I don't have any experience with hexo themes. But I think you will have to disable the default hexo zoom functionality. Could you please provide link to your website, So that I can have a look at the issue

**Comment by cutelittleturtle** [comment]
@sachinchoolur  

hi, the specific page is: https://cutelittleturtle.github.io/2017/09/07/ybysource/

Sorry it's mostly Chinese. You can find source files on its github repository.

Thanks.
