### ISSUE TITLE
Issue with dynamic videos (isVideo function)

### ISSUE THREAD

**Issue by denhaidash** [sachinchoolur/lightgallery.js#76]
Hi!

Could you please check your Plugin.prototype.isVideo function? It seems there is a logical error which doesn't allow me to create dynamic HTML5 video player.

You do the following check
`  if(!src) {
        throw new Error("Make sure that slide " + index + " has an image/video src");
    }`

and then the second one which will never happen if there is no src due to the first check
`    if (!src && html) {
        return {
            html5: true
        };
    }`

BTW, thanks for the cool library!

**Comment by rkimaoui** [comment]
for videos, i get this error too:  `Make sure that slide 0 has an image/video src`

**Comment by sachinchoolur** [comment]
Fixed
