### ISSUE TITLE
destroy function scrolls the page up

### ISSUE THREAD

**Issue by adirkandel** [sachinchoolur/lightgallery.js#78]
When i destroy the gallery it gets to these 2 lines:
    document.body.scrollTop = _this.prevScrollTop;
    document.documentElement.scrollTop = _this.prevScrollTop;

but _this.prevScrollTop is undefined the window scrolls to 0, means the top of the scroll position.

**Comment by alexrififi** [comment]
Same problem. Strange ...
Why move the scroll when destroying?

**Comment by parisek** [comment]
Its fixed in sibling plugin https://github.com/sachinchoolur/lightGallery/blob/master/dist/js/lightgallery.js#L1285 so I just comment out this lines and it works

@sachinchoolur Could you please fix it also here? Thank you

**Comment by piernik** [comment]
I have the same issue. I need to destroy lightgallery to refresh images. As I can see now it is the only way.
