### ISSUE TITLE
link to teamwave fails over https

### ISSUE THREAD

**Issue by runofthemill** [sachinchoolur/lightgallery.js#8]
looks like your server isn't configured correctly for https:

![screen shot 2016-08-03 at 8 09 27 pm](https://cloud.githubusercontent.com/assets/8418440/17389182/b1a7da92-59b6-11e6-9892-095c3ed919c3.png)

**Comment by sachinchoolur** [comment]
Thank you for pointing this out. I have updated the links 👍
