### ISSUE TITLE
swipeup and swipedown event

### ISSUE THREAD

**Issue by salihyasinseker** [sachinchoolur/lightgallery.js#82]
Can we close slideshow when swipeup or swipedown?

**Comment by larzon83** [comment]
I would love to have that, too :)

**Comment by larzon83** [comment]
Please reopen

**Comment by sachinchoolur** [comment]
Hey @larzon83,
This is already implemented in lightGallery v2.
Please let me know if you have any suggestions or feedback.

**Comment by larzon83** [comment]
> Hey @larzon83,
> This is already implemented in lightGallery v2.
> Please let me know if you have any suggestions or feedback.

Oh wow, didn't noticed :) Looks good, will upgrade...
