### ISSUE TITLE
Append new items to the gallery after initialization

### ISSUE THREAD

**Issue by adirkandel** [sachinchoolur/lightgallery.js#84]
I'm trying to find a way on how i can append new slides and thumbs after i initialize it.

For now, every time i add a new item to my gallery i initialize again the lightgallry so it rerenders the slides with the new added items and it's very not performant.

Does anyone know or encountered that issue and can help me solve it?

**Comment by usb248** [comment]
I would like this functionality too...
The API seems to be not enough succeeded...

**Comment by cnhuye** [comment]
+1

I working for a task , add or remove a image item from the gallery dynamiclly.  But right now seems no way to do that.

**Comment by giammin** [comment]
the only way I found is to `.destroy(true)` and re-initiate
