### ISSUE TITLE
Touch-Swipe not working

### ISSUE THREAD

**Issue by albuvee** [sachinchoolur/lightgallery.js#9]
On iOS 9.3.3 (Safari and Chrome), the swipe gesture to next/prev does not work. Nothing happens if i swipe right/left.

**Comment by sachinchoolur** [comment]
Hi @albuvee,
Thank you for reporting this
I've fixed the issue locally, I'll release the new version today with the fix.

**Comment by sachinchoolur** [comment]
The issue has been fixed. Please use latest version
