### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_2_lightgallery_js___default(...) is not a function

### ISSUE THREAD

**Issue by ccmyli** [sachinchoolur/lightgallery.js#91]
TypeError: __WEBPACK_IMPORTED_MODULE_2_lightgallery_js___default(...) is not a function

**Comment by justkost** [comment]
import 'lightgallery.js';
import 'lightgallery.js/dist/css/lightgallery.css';

lightGallery(document.getElementById('gallery'));
