### ISSUE TITLE
lightGallery has not initiated properly

### ISSUE THREAD

**Issue by mrcode86** [sachinchoolur/lightgallery.js#95]
Hi,

I try to use lightgallery with vuejs. I have created a component and use this:
```
mounted: function () {
        //document.getElementsByClassName("timeline-media");

        var targets = this.$refs.timelinemedia;
        if (!targets) return;
        console.log(targets);
        lightGallery(targets);
    }
```
I have tried booth refs and get the div by the id/class name and i get the same error message: lightGallery has not initiated properly.
When i check the error message i can se this: _lgUtils2.default is undefined

Whats wrong?

**Comment by usb248** [comment]
same problem

**Comment by viliusle** [comment]
Same problem when using js from jsdelivr cdn.
But taking js from github cdn works fine. oO

**Comment by zdb** [comment]
If you are using the jsDeliver CDN you need to de-select all the files and select the dist directory instead so your url will look like this:

https://cdn.jsdelivr.net/npm/lightgallery.js@1.1.1/dist/js/lightgallery.min.js

![image](https://user-images.githubusercontent.com/1664197/48235470-40a77900-e37b-11e8-8fec-67ca662ebf7e.png)
