### ISSUE TITLE
font-face block rendering...

### ISSUE THREAD

**Issue by GitMax42** [sachinchoolur/lightgallery.js#96]
would it be possible to use SVG buttons, so no extra download files?

**Comment by bramus** [comment]
Safari on iOS is affected by this issue. None of the close/next/prev/thumbs buttons render properly.

Screenshot:

![img_5086](https://user-images.githubusercontent.com/213073/43925201-ecdbd640-9c26-11e8-9b0b-20339b802bde.jpg)

**Comment by englishextra** [comment]
@bramus 
Usually this happens when the original source css has relative font face declaration like so `../fonts/some-font.woff`, and you compile that source CSS into bundle.css which resides at some other path. So that way you lose the path to font.
