### ISSUE TITLE
LightGalleryJs for Ionic 3 Angular 4.

### ISSUE THREAD

**Issue by Chethannp** [sachinchoolur/lightgallery.js#98]
Hey Sachinchoolur, do we have an angular  4 version of it now ? can you please help! All my 6 projects use lightgalleryjs and now I am developing an ionic 3 angular 4 project and was unable to get an info about your plugin. requesting you to kindly update on this please.

**Comment by Chethannp** [comment]
Any update on this please...?

**Comment by sachinchoolur** [comment]
Sorry for the late response - If anyone else is looking for the solution, please take a look this issue  https://github.com/sachinchoolur/lightgallery.js/issues/161
